/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * jfmFind.java
 *
 * Created on Mar 28, 2009, 3:08:47 PM
 */

package edu.uml.cs.GUIProgramming.SoundRepClient;

import edu.uml.cs.GUIProgramming.heines.*;
import javax.swing.JOptionPane;

/**
 *
 * @author JTLucas
 */
public class jfmFind extends javax.swing.JFrame {
  /** the following is required to keep NetBeans happy */
  static final long serialVersionUID = 0 ;

  private jfmAdvanced jfrmadv;

    /** Creates new form jfmFind */
    public jfmFind() {
      GUIUtilities.SetNetBeansCompatibleUIManager();
      initComponents();
    }
    public jfmFind(jfmAdvanced Advanced){
      GUIUtilities.SetNetBeansCompatibleUIManager();
      initComponents();
      jfrmadv = Advanced;

      jfrmadv.addComponentListener(new java.awt.event.ComponentAdapter() {
      @Override
        public void componentHidden(java.awt.event.ComponentEvent evt) {
          if(jfrmadv.getAdvancedFindActive()){
            setVisible(false);
          }
        }
      });

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    buttonGroup1 = new javax.swing.ButtonGroup();
    jcbTitle = new javax.swing.JCheckBox();
    jcbArtist = new javax.swing.JCheckBox();
    jcbGenre = new javax.swing.JCheckBox();
    jcbTags = new javax.swing.JCheckBox();
    jtfTitle = new javax.swing.JTextField();
    jtfArtist = new javax.swing.JTextField();
    jtfGenre = new javax.swing.JTextField();
    jtfTags = new javax.swing.JTextField();
    jbtnAdvanced = new javax.swing.JButton();
    jbtnFind = new javax.swing.JButton();
    jrbAll = new javax.swing.JRadioButton();
    jrbAny = new javax.swing.JRadioButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setTitle("Find");
    setAlwaysOnTop(true);
    setMinimumSize(new java.awt.Dimension(297, 208));
    setResizable(false);

    jcbTitle.setText("Title");

    jcbArtist.setText("Artist");

    jcbGenre.setText("Genre");

    jcbTags.setText("Tags");

    jtfTitle.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jtfTitleActionPerformed(evt);
      }
    });

    jtfArtist.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jtfArtistActionPerformed(evt);
      }
    });

    jtfGenre.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jtfGenreActionPerformed(evt);
      }
    });

    jtfTags.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jtfTagsActionPerformed(evt);
      }
    });

    jbtnAdvanced.setText("Advanced");
    jbtnAdvanced.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jbtnAdvancedActionPerformed(evt);
      }
    });

    jbtnFind.setText("Find");
    jbtnFind.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jbtnFindActionPerformed(evt);
      }
    });

    buttonGroup1.add(jrbAll);
    jrbAll.setSelected(true);
    jrbAll.setText("Match ALL of these fields");

    buttonGroup1.add(jrbAny);
    jrbAny.setText("Match ANY of these fields");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jcbTitle)
          .addComponent(jcbArtist)
          .addComponent(jcbGenre)
          .addComponent(jcbTags))
        .addGap(39, 39, 39)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jtfTags, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
          .addComponent(jtfGenre, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
          .addComponent(jtfArtist, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
          .addComponent(jtfTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap())
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addGap(57, 57, 57)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addComponent(jbtnAdvanced)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
            .addComponent(jbtnFind, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
              .addComponent(jrbAny, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addComponent(jrbAll, javax.swing.GroupLayout.Alignment.LEADING))
            .addGap(22, 22, 22)))
        .addGap(53, 53, 53))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jcbTitle)
          .addComponent(jtfTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jcbArtist)
          .addComponent(jtfArtist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jcbGenre)
          .addComponent(jtfGenre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jcbTags)
          .addComponent(jtfTags, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addComponent(jrbAll)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(jrbAny)
        .addGap(25, 25, 25)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jbtnFind)
          .addComponent(jbtnAdvanced))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

    private void jbtnFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnFindActionPerformed
      // this will start the search
      setVisible(false);
}//GEN-LAST:event_jbtnFindActionPerformed

    private void jtfTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfTitleActionPerformed
      // If enter key is pressed run search
      jbtnFindActionPerformed(evt);
    }//GEN-LAST:event_jtfTitleActionPerformed

    private void jtfArtistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfArtistActionPerformed
      // If enter key is pressed run search
      jbtnFindActionPerformed(evt);
    }//GEN-LAST:event_jtfArtistActionPerformed

    private void jtfGenreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfGenreActionPerformed
      // If enter key is pressed run search
      jbtnFindActionPerformed(evt);
    }//GEN-LAST:event_jtfGenreActionPerformed

    private void jtfTagsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfTagsActionPerformed
      // If enter key is pressed run search
      jbtnFindActionPerformed(evt);
    }//GEN-LAST:event_jtfTagsActionPerformed

    private void jbtnAdvancedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAdvancedActionPerformed
      jfrmadv.setVisible(true);
    }//GEN-LAST:event_jbtnAdvancedActionPerformed

    public void ResetFields() {
      //Reset all the text fields
      jtfTitle.setText("");
      jtfArtist.setText("");
      jtfGenre.setText("");
      jtfTags.setText("");
      //Reset all the check box values
      jcbTitle.setSelected(false);
      jcbArtist.setSelected(false);
      jcbGenre.setSelected(false);
      jcbTags.setSelected(false);
      //Set jrbAll as the default search option
      jrbAll.setSelected(true);
    }

    public String getSearchstrTitle() {
      if(jcbTitle.isSelected()){
        return jtfTitle.getText();
      }
      else {
        return "";
      }
    }

    public String getSearchstrArtist() {
      if(jcbArtist.isSelected()){
        return jtfArtist.getText();
      }
      else {
        return "";
      }
    }

    public String getSearchstrGenre() {
      if(jcbGenre.isSelected()){
        return jtfGenre.getText();
      }
      else {
        return "";
      }
    }

    public String getSearchstrTags() {
      if(jcbTags.isSelected()){
        return jtfTags.getText();
      }
      else {
        return "";
      }
    }

    public boolean getJCBTitle(){
      return jcbTitle.isSelected();
    }

    public boolean getJCBArtist(){
      return jcbArtist.isSelected();
    }

    public boolean getJCBGenre(){
      return jcbGenre.isSelected();
    }

    public boolean getJCBTags(){
      return jcbTags.isSelected();
    }

    public boolean getJRBAll(){
      return jrbAll.isSelected();
    }

    public boolean getJRBAny(){
      return jrbAny.isSelected();
    }

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfmFind().setVisible(true);
            }
        });
    }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.ButtonGroup buttonGroup1;
  private javax.swing.JButton jbtnAdvanced;
  private javax.swing.JButton jbtnFind;
  private javax.swing.JCheckBox jcbArtist;
  private javax.swing.JCheckBox jcbGenre;
  private javax.swing.JCheckBox jcbTags;
  private javax.swing.JCheckBox jcbTitle;
  private javax.swing.JRadioButton jrbAll;
  private javax.swing.JRadioButton jrbAny;
  private javax.swing.JTextField jtfArtist;
  private javax.swing.JTextField jtfGenre;
  private javax.swing.JTextField jtfTags;
  private javax.swing.JTextField jtfTitle;
  // End of variables declaration//GEN-END:variables

}
