/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewMain.java
 *
 * Created on Mar 31, 2009, 9:37:41 AM
 */

package GUI;

import java.net.URL;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @authors Jim Ebert and Elizabeth Tran
 */
public class NewMain extends javax.swing.JFrame {

    /**
     * A vector of the column names to the table model  dtm
     */
    private Vector<String> columnNames = new Vector<String>();
    /**
     * The non-editable table model used in this application
     */
    private ETTableModel dtm = new ETTableModel();
    /**
     * A vector of the sound library entries
     */
    private Vector<SoundLibraryEntry> stored_results;

    /**
     * The streaming thread initialized to null
     */
    private StreamThread stream_thread = null;

    /** Creates new form NewMain */
    public NewMain() {

        //Adds the titles to the TableModel
        columnNames.add( "Title" );
        columnNames.add( "Artist" );
        columnNames.add( "Genre" );
        columnNames.add( "Tags" );
        columnNames.add( "Mime Type" );
   
        initComponents();

        //creates the table model
        dtm = new ETTableModel( new Vector<Vector<String>>(), columnNames );

        try{
            //SoundLibraryQuery query = new SoundLibraryQuery( "SELECT * FROM library WHERE MATCH (Tags) AGAINST ('plop' IN BOOLEAN MODE)" );
            SoundLibraryQuery query = new SoundLibraryQuery();
            Vector<SoundLibraryEntry> results = query.executeQuery();
            stored_results = results;
            //for( SoundLibraryEntry entry: results ){
            //    System.out.println( entry.getURL().toURI() + " " + entry.getTitle() + " " + entry.getAuthor() + " " + entry.getGenre() + " " + entry.getTags() );
            //}
            //Adds the rows to the table
            for( SoundLibraryEntry entry: results ){
                Vector<String> new_row = new Vector<String>();
                new_row.add( entry.getTitle() );
                new_row.add( entry.getAuthor() );
                new_row.add( entry.getGenre() );
                new_row.add( entry.getTags() );
                new_row.add( entry.getMimeType() );

                dtm.addRow( new_row );
            }
        }
        catch( Exception ex ){
           System.err.println( ex );
        }

        //Sets the jTable to the ETTableModel
        jtbleSongs.setModel(dtm);
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jScrollPane = new javax.swing.JScrollPane();
        jtbleSongs = new javax.swing.JTable();
        jtbleSongs.setModel(new DefaultTableModel());
        jpnlMusicPlayer = new javax.swing.JPanel();
        jStreambtn = new javax.swing.JButton();
        jStopbttn = new javax.swing.JButton();
        jbrSongProgress = new javax.swing.JProgressBar();
        jlblSongTitle = new java.awt.Label();
        jlblSearch = new java.awt.Label();
        jtxtSearch = new java.awt.TextField();
        jMenuBar = new javax.swing.JMenuBar();
        jmnuFile = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jmnuExit = new javax.swing.JMenuItem();
        jmnuEdit = new javax.swing.JMenu();
        jmnuSearch = new javax.swing.JMenuItem();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 335, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 204, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sound Library");

        jtbleSongs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        jScrollPane.setViewportView(jtbleSongs);

        jpnlMusicPlayer.setBorder(javax.swing.BorderFactory.createTitledBorder("Music Player"));

        jStreambtn.setText("Stream");
        jStreambtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jStreambtnActionPerformed(evt);
            }
        });

        jStopbttn.setText("Stop");
        jStopbttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jStopbttnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpnlMusicPlayerLayout = new javax.swing.GroupLayout(jpnlMusicPlayer);
        jpnlMusicPlayer.setLayout(jpnlMusicPlayerLayout);
        jpnlMusicPlayerLayout.setHorizontalGroup(
            jpnlMusicPlayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlMusicPlayerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnlMusicPlayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnlMusicPlayerLayout.createSequentialGroup()
                        .addComponent(jStreambtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jStopbttn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(149, 149, 149))
                    .addGroup(jpnlMusicPlayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jlblSongTitle, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbrSongProgress, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jpnlMusicPlayerLayout.setVerticalGroup(
            jpnlMusicPlayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlMusicPlayerLayout.createSequentialGroup()
                .addComponent(jlblSongTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbrSongProgress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jpnlMusicPlayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jStreambtn)
                    .addComponent(jStopbttn))
                .addContainerGap())
        );

        jlblSearch.setText("Search");

        jmnuFile.setText("File");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Upload...");
        jmnuFile.add(jMenuItem1);

        jmnuExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        jmnuExit.setText("Exit");
        jmnuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmnuExitActionPerformed(evt);
            }
        });
        jmnuFile.add(jmnuExit);

        jMenuBar.add(jmnuFile);

        jmnuEdit.setText("Edit");

        jmnuSearch.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
        jmnuSearch.setText("Advanced Search...");
        jmnuEdit.add(jmnuSearch);

        jMenuBar.add(jmnuEdit);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 656, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpnlMusicPlayer, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlblSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlblSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jpnlMusicPlayer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Done when closing out of the program, exit button selected
     * @param evt a java action event
     */
    private void jmnuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmnuExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jmnuExitActionPerformed

    private void jStreambtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jStreambtnActionPerformed
        // TODO add your handling code here:
        try{
                   URL stream_url = stored_results.elementAt( jtbleSongs.getSelectedRow() ).getURL();
                   if( stream_thread == null ){
                       stream_thread = new StreamThread( stream_url );
                   }
                   else{
                       stream_thread.setStream( stream_url );
                   }
                   //updateStatusText( "Streaming: " + dtm.getValueAt( jtbleSongs.getSelectedRow(), 0 ) );
                   stream_thread.run();
               }
               catch( Exception exception ){
                   System.err.println( exception );
               }
    }//GEN-LAST:event_jStreambtnActionPerformed

    private void jStopbttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jStopbttnActionPerformed
        // TODO add your handling code here:
        stopAudio();
    }//GEN-LAST:event_jStopbttnActionPerformed

    /**
     * Stops the streaming of a thread, if there is one streaming.
     */
    public void stopAudio(){
        if( stream_thread != null ) stream_thread.requestStop();
    }

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame jFrame1;
    private javax.swing.JMenuBar jMenuBar;
    /** Upload menu item brings up the upload dialog box */
    private javax.swing.JMenuItem jMenuItem1;
    /** The ScrollPane that holds the TableModel */
    private javax.swing.JScrollPane jScrollPane;
    /** Stops the Streaming of a thread */
    private javax.swing.JButton jStopbttn;
    /** Streams the selected sound file */
    private javax.swing.JButton jStreambtn;
    /** Shows the songs progress */
    private javax.swing.JProgressBar jbrSongProgress;
    /** label to show the user where to search */
    private java.awt.Label jlblSearch;
    /** holds the title of the song currently playing */
    private java.awt.Label jlblSongTitle;
    /** Edit menu button */
    private javax.swing.JMenu jmnuEdit;
    /** Exit menu item */
    private javax.swing.JMenuItem jmnuExit;
    /** File menu button */
    private javax.swing.JMenu jmnuFile;
    /** Search menu item */
    private javax.swing.JMenuItem jmnuSearch;
    /** Panel that holds the music player UI */
    private javax.swing.JPanel jpnlMusicPlayer;
    /** table that holds the song data */
    private javax.swing.JTable jtbleSongs;
    /** text field used to search by song title */
    private java.awt.TextField jtxtSearch;
    // End of variables declaration//GEN-END:variables

}
