/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewMain.java
 *
 * Created on Mar 31, 2009, 9:37:41 AM
 */

package soundlibrary;

import java.util.Vector;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jim Ebert
 */
public class NewMain extends javax.swing.JFrame {

    private Vector<String> columnNames = new Vector<String>();
    private DefaultTableModel dtm = new DefaultTableModel();
    private Vector<SoundLibraryEntry> stored_results;

    /** Creates new form NewMain */
    public NewMain() {

        columnNames.add( "Title" );
        columnNames.add( "Artist" );
        columnNames.add( "Genre" );
        columnNames.add( "Tags" );
        columnNames.add( "Mime Type" );
   
        initComponents();

        dtm = new DefaultTableModel( new Vector<Vector<String>>(), columnNames );

        try{
            //SoundLibraryQuery query = new SoundLibraryQuery( "SELECT * FROM library WHERE MATCH (Tags) AGAINST ('plop' IN BOOLEAN MODE)" );
            SoundLibraryQuery query = new SoundLibraryQuery();
            Vector<SoundLibraryEntry> results = query.executeQuery();
            stored_results = results;
            //for( SoundLibraryEntry entry: results ){
            //    System.out.println( entry.getURL().toURI() + " " + entry.getTitle() + " " + entry.getAuthor() + " " + entry.getGenre() + " " + entry.getTags() );
            //}
            for( SoundLibraryEntry entry: results ){
                Vector<String> new_row = new Vector<String>();
                new_row.add( entry.getTitle() );
                new_row.add( entry.getAuthor() );
                new_row.add( entry.getGenre() );
                new_row.add( entry.getTags() );
                new_row.add( entry.getMimeType() );

                dtm.addRow( new_row );
            }
        }
        catch( Exception ex ){
           System.err.println( ex );
        }

        jtbleSongs.setModel(dtm);
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtbleSongs = new javax.swing.JTable();
        jtbleSongs.setModel(new DefaultTableModel());
        jMenuBar1 = new javax.swing.JMenuBar();
        jmnuFile = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jmnuExit = new javax.swing.JMenuItem();
        jmnuEdit = new javax.swing.JMenu();
        jmnuSearch = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jtbleSongs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        jScrollPane1.setViewportView(jtbleSongs);

        jmnuFile.setText("File");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Upload...");
        jmnuFile.add(jMenuItem1);

        jmnuExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        jmnuExit.setText("Exit");
        jmnuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmnuExitActionPerformed(evt);
            }
        });
        jmnuFile.add(jmnuExit);

        jMenuBar1.add(jmnuFile);

        jmnuEdit.setText("Edit");

        jmnuSearch.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
        jmnuSearch.setText("Search...");
        jmnuEdit.add(jmnuSearch);

        jMenuBar1.add(jmnuEdit);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 656, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(105, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Done when closing out of the program, exit button selected
     * @param evt a java action event
     */
    private void jmnuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmnuExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jmnuExitActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    /** Upload menu item brings up the upload dialog box */
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    /** Edit menu button */
    private javax.swing.JMenu jmnuEdit;
    /** Exit menu item */
    private javax.swing.JMenuItem jmnuExit;
    /** File menu button */
    private javax.swing.JMenu jmnuFile;
    /** Search menu item */
    private javax.swing.JMenuItem jmnuSearch;
    /** table that holds the song data */
    private javax.swing.JTable jtbleSongs;
    // End of variables declaration//GEN-END:variables

}
