/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JMUploadPanel.java
 *
 * Created on Apr 1, 2009, 12:33:39 AM
 */

package SoundPack;

import edu.uml.sl.*;
import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
import org.w3c.dom.Node;
import org.w3c.dom.NodeList;

/**
 *
 * @author James
 */
public class JMUploadPanel extends javax.swing.JPanel {

    JFileChooser jfc = new JFileChooser();

    /** Creates new form JMUploadPanel */
    public JMUploadPanel() {
        initComponents();
        jfc.addChoosableFileFilter(new SoundFilter());
        jlblMessage.setText("Please select a file");
    }

    public void actionPerformed(ActionEvent e){

        if(e.getSource() == jbttnOpen){
            int val = jfc.showOpenDialog(JMUploadPanel.this);
            if(val == jfc.APPROVE_OPTION){
                jtfFile.setText(jfc.getSelectedFile().getPath());
            }
        }

        if(e.getSource() == jbttnUpload){
            jlblMessage.setText("Please wait...");
            SoundLibraryUpload update = new SoundLibraryUpload();
            update.setFilePath( jtfFile.getText() );
            update.setTitle( jtfTitle.getText() );
            update.setAuthor( jtfArtist.getText() );
            update.setGenre( jtfGenre.getText() );
            update.setTags( jtfTags.getText() );

            //Now to send the update
            try{
                update.executeUpload();
                NodeList warnings = update.getReply().getElementsByTagName( "Warning" );
                 for (int i = 0; i < warnings.getLength(); i++) {
                    Node entry = warnings.item(i);
                    System.out.println( entry.getTextContent() );
                 }
            }
            catch( Exception exception ){
                System.err.println( exception.getMessage() );
                jlblMessage.setForeground(Color.RED);
                jlblMessage.setText(exception.getMessage());
            }
            jlblMessage.setForeground(Color.BLACK);
            jlblMessage.setText("Completed, please enter another file");
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jlblFile = new javax.swing.JLabel();
    jlblTrack = new javax.swing.JLabel();
    jlblArtist = new javax.swing.JLabel();
    jlblGenre = new javax.swing.JLabel();
    jlblTags = new javax.swing.JLabel();
    jtfFile = new javax.swing.JTextField();
    jtfTitle = new javax.swing.JTextField();
    jtfArtist = new javax.swing.JTextField();
    jtfGenre = new javax.swing.JTextField();
    jtfTags = new javax.swing.JTextField();
    jbttnOpen = new javax.swing.JButton();
    jbttnUpload = new javax.swing.JButton();
    jlblMessage = new javax.swing.JLabel();

    jlblFile.setText("File Name:");

    jlblTrack.setText("Track Title:");

    jlblArtist.setText("Artist:");

    jlblGenre.setText("Genre:");

    jlblTags.setText("Tags:");

    jbttnOpen.setText("Open");
    jbttnOpen.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jbttnOpenActionPerformed(evt);
      }
    });

    jbttnUpload.setText("Upload");
    jbttnUpload.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jbttnUploadActionPerformed(evt);
      }
    });

    jlblMessage.setText("Message Here");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(layout.createSequentialGroup()
                .addComponent(jlblTags)
                .addGap(18, 18, 18)
                .addComponent(jtfTags, javax.swing.GroupLayout.DEFAULT_SIZE, 311, Short.MAX_VALUE))
              .addGroup(layout.createSequentialGroup()
                .addComponent(jbttnOpen)
                .addGap(2, 2, 2)
                .addComponent(jbttnUpload, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE))
              .addGroup(layout.createSequentialGroup()
                .addComponent(jlblArtist)
                .addGap(18, 18, 18)
                .addComponent(jtfArtist, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
              .addGroup(layout.createSequentialGroup()
                .addComponent(jlblGenre)
                .addGap(18, 18, 18)
                .addComponent(jtfGenre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
              .addGroup(layout.createSequentialGroup()
                .addComponent(jlblFile)
                .addGap(18, 18, 18)
                .addComponent(jtfFile, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE))
              .addGroup(layout.createSequentialGroup()
                .addComponent(jlblTrack)
                .addGap(18, 18, 18)
                .addComponent(jtfTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGap(24, 24, 24))
          .addGroup(layout.createSequentialGroup()
            .addComponent(jlblMessage)
            .addContainerGap(338, Short.MAX_VALUE))))
    );

    layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jlblArtist, jlblFile, jlblGenre, jlblTags, jlblTrack});

    layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jtfArtist, jtfFile, jtfGenre, jtfTags, jtfTitle});

    layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jbttnOpen, jbttnUpload});

    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jlblFile)
          .addComponent(jtfFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jlblTrack)
          .addComponent(jtfTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jlblArtist)
          .addComponent(jtfArtist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jlblGenre)
          .addComponent(jtfGenre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jlblTags)
          .addComponent(jtfTags, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
        .addComponent(jlblMessage)
        .addGap(18, 18, 18)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jbttnOpen)
          .addComponent(jbttnUpload))
        .addContainerGap())
    );
  }// </editor-fold>//GEN-END:initComponents

    private void jbttnOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbttnOpenActionPerformed
        // TODO add your handling code here:
        actionPerformed(evt);
    }//GEN-LAST:event_jbttnOpenActionPerformed

    private void jbttnUploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbttnUploadActionPerformed
        // TODO add your handling code here:
        actionPerformed(evt);
    }//GEN-LAST:event_jbttnUploadActionPerformed


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton jbttnOpen;
  private javax.swing.JButton jbttnUpload;
  private javax.swing.JLabel jlblArtist;
  private javax.swing.JLabel jlblFile;
  private javax.swing.JLabel jlblGenre;
  private javax.swing.JLabel jlblMessage;
  private javax.swing.JLabel jlblTags;
  private javax.swing.JLabel jlblTrack;
  private javax.swing.JTextField jtfArtist;
  private javax.swing.JTextField jtfFile;
  private javax.swing.JTextField jtfGenre;
  private javax.swing.JTextField jtfTags;
  private javax.swing.JTextField jtfTitle;
  // End of variables declaration//GEN-END:variables

}
