/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * jfrmMain.java
 *
 * Created on Mar 28, 2009, 1:09:27 PM
 */

package edu.uml.cs.GUIProgramming.SoundRepClient;

import edu.uml.cs.GUIProgramming.heines.*;
import java.awt.event.FocusEvent;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author JTLucas
 */
public class jfrmMain extends javax.swing.JFrame {

  jfmFind jfrmfind = new jfmFind();
  jpSearch jPanelSearch = new jpSearch();

    /** Creates new form jfrmMain */
    public jfrmMain() {
      GUIUtilities.SetNetBeansCompatibleUIManager();
      initComponents();

      jfrmfind.addComponentListener(new java.awt.event.ComponentAdapter() {
      @Override
      public void componentHidden(java.awt.event.ComponentEvent evt) {
        SearchDatabase(jfrmfind.getSearchstrTitle(), jfrmfind.getSearchstrArtist(), jfrmfind.getSearchstrGenre(), jfrmfind.getSearchstrTags());
      }
    });
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jtpMainTab = new javax.swing.JTabbedPane();
    jpMain = new javax.swing.JPanel();
    jMenuBar1 = new javax.swing.JMenuBar();
    jmFile = new javax.swing.JMenu();
    jmiExit = new javax.swing.JMenuItem();
    jmEdit = new javax.swing.JMenu();
    jmiFind = new javax.swing.JMenuItem();
    jmOptions = new javax.swing.JMenu();
    jmiSettings = new javax.swing.JMenuItem();
    jmHelp = new javax.swing.JMenu();
    jmiAbout = new javax.swing.JMenuItem();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    javax.swing.GroupLayout jpMainLayout = new javax.swing.GroupLayout(jpMain);
    jpMain.setLayout(jpMainLayout);
    jpMainLayout.setHorizontalGroup(
      jpMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 537, Short.MAX_VALUE)
    );
    jpMainLayout.setVerticalGroup(
      jpMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 303, Short.MAX_VALUE)
    );

    jtpMainTab.addTab("Main", jpMain);

    jmFile.setMnemonic('f');
    jmFile.setText("File");

    jmiExit.setMnemonic('x');
    jmiExit.setText("Exit");
    jmiExit.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jmiExitActionPerformed(evt);
      }
    });
    jmFile.add(jmiExit);

    jMenuBar1.add(jmFile);

    jmEdit.setMnemonic('e');
    jmEdit.setText("Edit");

    jmiFind.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
    jmiFind.setMnemonic('f');
    jmiFind.setText("Find");
    jmiFind.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jmiFindActionPerformed(evt);
      }
    });
    jmEdit.add(jmiFind);

    jMenuBar1.add(jmEdit);

    jmOptions.setMnemonic('o');
    jmOptions.setText("Options");

    jmiSettings.setMnemonic('s');
    jmiSettings.setText("Settings");
    jmOptions.add(jmiSettings);

    jMenuBar1.add(jmOptions);

    jmHelp.setMnemonic('h');
    jmHelp.setText("Help");

    jmiAbout.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
    jmiAbout.setMnemonic('a');
    jmiAbout.setText("About");
    jmHelp.add(jmiAbout);

    jMenuBar1.add(jmHelp);

    setJMenuBar(jMenuBar1);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jtpMainTab, javax.swing.GroupLayout.DEFAULT_SIZE, 542, Short.MAX_VALUE)
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jtpMainTab, javax.swing.GroupLayout.DEFAULT_SIZE, 331, Short.MAX_VALUE)
        .addContainerGap())
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

    private void jmiExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiExitActionPerformed
      //Exit the application safely
      System.exit(0);
    }//GEN-LAST:event_jmiExitActionPerformed

    private void jmiFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiFindActionPerformed
      jfrmfind.ClearTextFields();
      jfrmfind.setVisible(true);
    }//GEN-LAST:event_jmiFindActionPerformed

    private void SearchDatabase ( String SearchstrTitle, String SearchstrArtist, String SearchstrGenre, String SearchstrTags ) {
      int tabcount = jtpMainTab.getComponentCount();
      jtpMainTab.addTab("Search", jPanelSearch);
      //jtpMainTab.setSelectedIndex(tabcount);
    }

    private void SearchDatabase ( String AdvancedSearch ){

    }

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfrmMain().setVisible(true);
            }
        });
    }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JMenuBar jMenuBar1;
  private javax.swing.JMenu jmEdit;
  private javax.swing.JMenu jmFile;
  private javax.swing.JMenu jmHelp;
  private javax.swing.JMenu jmOptions;
  private javax.swing.JMenuItem jmiAbout;
  private javax.swing.JMenuItem jmiExit;
  private javax.swing.JMenuItem jmiFind;
  private javax.swing.JMenuItem jmiSettings;
  private javax.swing.JPanel jpMain;
  private javax.swing.JTabbedPane jtpMainTab;
  // End of variables declaration//GEN-END:variables

}
